language: node_js
node_js:
  - "7"

cache:
  directories:
    - "node_modules"

services:
  - postgresql

before_install:
  - npm install mocha -g

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - export LAMPS_DB_DEV=travis_ci_test
  - export LAMPS_USER_DEV=postgres
  - export LAMPS_PW_DEV=""
  - export LAMPS_SECRET_DEV=Dev
  - export SESSION_SECRET_DEV=session
  - export SAMPLE_ADMIM_PW=test11034
  - node config/dbInitialize.js

script:
  - npm run travisTest

after_script: 
  - npm run coveralls

addons:
  postgresql: "9.4"